### ISSUE TITLE
Concurrent map writes in tf-apko

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/terraform-provider-apko#102]
Example trace:
```
Stack trace from the terraform-provider-apko_v0.8.8 plugin:

fatal error: concurrent map writes

goroutine 192 [running]:
github.com/chainguard-dev/terraform-provider-apko/internal/provider.doBuild.func1()
	github.com/chainguard-dev/terraform-provider-apko/internal/provider/build.go:169 +0xd2e
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.2.0/errgroup/errgroup.go:72 +0xa5

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0xc000280a20)
	github.com/hashicorp/go-plugin@v1.4.9/server.go:474 +0x14d7
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.Serve({0x1145bdc, 0x29}, 0xc00069bc60, {0x0, 0x0, 0x0})
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:312 +0xba5
github.com/hashicorp/terraform-plugin-framework/providerserver.Serve({0x12d4cd8?, 0xc0001a6000?}, 0xc0001af050, {{0x1145bdc?, 0x5?}, 0x5?, 0x45?})
	github.com/hashicorp/terraform-plugin-framework@v1.3.1/providerserver/providerserver.go:114 +0x290
main.main()
	github.com/chainguard-dev/terraform-provider-apko/main.go:27 +0x11a

goroutine 85 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0x1166c23?)
	github.com/hashicorp/go-plugin@v1.4.9/grpc_broker.go:124 +0x67
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0xc000122500)
	github.com/hashicorp/go-plugin@v1.4.9/grpc_broker.go:414 +0x44
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
	github.com/hashicorp/go-plugin@v1.4.9/grpc_server.go:88 +0x46a

goroutine 86 [IO wait]:
internal/poll.runtime_pollWait(0x7fe025545720, 0x72)
	runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc000118a80?, 0xc00025e000?, 0x1)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000118a80, {0xc00025e000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc0001b0140, {0xc00025e000?, 0x400?, 0xf5bde0?})
	os/file.go:119 +0x5e
bufio.(*Reader).Read(0xc0004e7740, {0xc00073c400, 0x400, 0x0?})
	bufio/bufio.go:237 +0x1bb
github.com/hashicorp/go-plugin.copyChan({0x12df4d8, 0xc00023cd20}, 0x0?, {0x12ce000?, 0xc0001b0140?})
	github.com/hashicorp/go-plugin@v1.4.9/grpc_stdio.go:184 +0x1f6
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.9/grpc_stdio.go:40 +0xf5

goroutine 87 [IO wait]:
internal/poll.runtime_pollWait(0x7fe025545540, 0x72)
	runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc000118b40?, 0xc00025f000?, 0x1)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000118b40, {0xc00025f000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc0001b0158, {0xc00025f000?, 0x400?, 0xf5bde0?})
	os/file.go:119 +0x5e
bufio.(*Reader).Read(0xc0004eb740, {0xc00073c800, 0x400, 0x0?})
	bufio/bufio.go:237 +0x1bb
github.com/hashicorp/go-plugin.copyChan({0x12df4d8, 0xc00023cd20}, 0x0?, {0x12ce000?, 0xc0001b0158?})
	github.com/hashicorp/go-plugin@v1.4.9/grpc_stdio.go:184 +0x1f6
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.9/grpc_stdio.go:41 +0x185

goroutine 89 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a

goroutine 90 [chan receive]:
github.com/hashicorp/go-plugin.Serve.func3()
	github.com/hashicorp/go-plugin@v1.4.9/server.go:439 +0x75
created by github.com/hashicorp/go-plugin.Serve
	github.com/hashicorp/go-plugin@v1.4.9/server.go:436 +0x12aa

goroutine 91 [IO wait]:
internal/poll.runtime_pollWait(0x7fe025545810, 0x72)
	runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc000596700?, 0x7fe025782c78?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000596700)
	internal/poll/fd_unix.go:614 +0x234
net.(*netFD).accept(0xc000596700)
	net/fd_unix.go:172 +0x35
net.(*UnixListener).accept(0x46572e?)
	net/unixsock_posix.go:166 +0x1c
net.(*UnixListener).Accept(0xc000124d20)
	net/unixsock.go:260 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc0002fe1e0, {0x12d3640?, 0xc0000fe5a0})
	google.golang.org/grpc@v1.55.0/server.go:821 +0x475
github.com/hashicorp/go-plugin.(*GRPCServer).Serve(0xc0001ea240, {0x12d3640?, 0xc0000fe5a0?})
	github.com/hashicorp/go-plugin@v1.4.9/grpc_server.go:153 +0x71

```

**Comment by imjasonh** [comment]
Should also run tests with `-race`, here and in all the various providers.
