### ISSUE TITLE
terraform apply panics when no arch is specified

### ISSUE THREAD

**Issue by joshrwolf** [chainguard-dev/terraform-provider-apko#63]
panics when the provider + data source config `arch` is empty:

```
❯ terraform apply
data.apko_config.image: Reading...
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ReadDataSource request was cancelled.
╵

Stack trace from the terraform-provider-apko_v0.8.3 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 67 [running]:
github.com/chainguard-dev/terraform-provider-apko/internal/provider.unify({0x14000090e00, 0x2, 0x101544030?}, {0x1022e1d28, 0x0, 0x0})
        github.com/chainguard-dev/terraform-provider-apko/internal/provider/config_data_source.go:232 +0xc94
github.com/chainguard-dev/terraform-provider-apko/internal/provider.(*ConfigDataSource).resolvePackageList(_, {{{0x14000384420, 0x1, 0x1}, {0x14000384430, 0x1, 0x1}, {0x14000090e00, 0x2, 0x2}}, ...})
        github.com/chainguard-dev/terraform-provider-apko/internal/provider/config_data_source.go:199 +0x2ec
github.com/chainguard-dev/terraform-provider-apko/internal/provider.(*ConfigDataSource).Read(0x14000114e40, {0x101a42a90, 0x140005d30e0}, {{{{0x101a48fa8, 0x140001915c0}, {0x101881100, 0x140004e54a0}}, {0x101a4add8, 0x140005f9200}}, {{{0x0, ...}, ...}, ...}}, ...)
        github.com/chainguard-dev/terraform-provider-apko/internal/provider/config_data_source.go:131 +0x6a0
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0x140003c86e0, {0x101a42a90, 0x140005d30e0}, 0x140005d33e0, 0x140001695e8)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_readdatasource.go:75 +0x394
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0x140003c86e0, {0x101a42a90?, 0x140005d2780?}, 0x14000090240)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_readdatasource.go:52 +0x1b0
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0x140005b80a0, {0x101a42a90?, 0x14000382c60?}, 0x140000581e0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:656 +0x368
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x1019e9e40?, 0x140005b80a0}, {0x101a42a90, 0x14000382c60}, 0x140000fc0e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:455 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140003d6000, {0x101a496c0, 0x14000103380}, 0x140004d2000, 0x140005d2000, 0x102298a90, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xc64
google.golang.org/grpc.(*Server).handleStream(0x140003d6000, {0x101a496c0, 0x14000103380}, 0x140004d2000, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x290

Error: The terraform-provider-apko_v0.8.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by joshrwolf** [comment]
minimum reproducible:

```hcl
provider "apko" {
  extra_repositories = ["https://packages.wolfi.dev/os"]
  extra_keyring      = ["https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"]
}

data "apko_config" "image" {
  config_contents = file("${path.module}/apko.yaml")
}

resource "apko_build" "image" {
  repo   = "ttl.sh/apanic"
  config = data.apko_config.image.config
}
```
